classDiagram

class liga_naranja {
    +id_liga_naranja: INT
    +nombre: VARCHAR
    +region: VARCHAR
    +cantidad_entrenadores: INT
    +cantidad_gimnasios: INT
    +cantidad_pokemones: INT
    +cantidad_combates: INT
    +fecha_inicio: DATE
    +fecha_fin: DATE
    +estado:('activa', 'inactiva', 'finalizada')

}

class entrenador {
    +id_entrenador: INT
    +nombre: VARCHAR
    +edad: INT
    +genero:VARCHAR
    +region: VARCHAR
    +tipo: VARCHAR
    +cantidad_pokemones: INT
    +cantidad_combates_ganados: INT
    +cantidad_combates_perdidos: INT
    +fecha_registro: DATE
    +id_liga_naranja: INT
}

class gimnasio {
    +id_gimnasio: INT
    +nombre: VARCHAR
    +ciudad: VARCHAR
    +region: VARCHAR
    +tipo: VARCHAR
    +cantidad_entrenadores: INT
    +cantidad_pokemones: INT
    +cantidad_combates: INT
    +fecha_fundacion: DATE
    +id_lider: INT
    +id_liga_naranja: INT
}

class pokemon {
    +id_pokemon: INT
    +nombre: VARCHAR
    +tipo: VARCHAR
    +nivel: INT
    +habilidad_especial: VARCHAR
    +fecha_captura: DATE
    +id_entrenador: INT
}

class combate {
    +id_combate: INT
    +fecha: DATE
    +ubicacion: VARCHAR
    +estado: ('pendiente', 'en curso', 'finalizado')
    +puntos_entregados: INT
    +id_entrenador_1: INT
    +id_entrenador_2: INT
    +id_gimnasio: INT
}

liga_naranja "1" -- "0..*" entrenador : tiene >
liga_naranja "1" -- "0..*" gimnasio : tiene >
liga_naranja "1" -- "0..*" combate : organiza >
entrenador "1" -- "0..*" pokemon : posee >
entrenador "1" -- "0..*" combate : participa >
gimnasio "1" -- "1" entrenador : liderado_por >
gimnasio "1" -- "0..*" combate : sede_de >
entrenador "1" -- "0..*" gimnasio : desafia >
entrenador "1" -- "0..*" entrenador : combate_con >
combate "1" -- "1" entrenador : entre
combate "1" -- "1" entrenador : entre
combate "1" -- "1" gimnasio : en
gimnasio "1" -- "0..*" entrenador : tiene >
gimnasio "1" -- "0..*" pokemon : tiene >
pokemon "1" -- "1" entrenador : pertenece_a > 
pokemon "1" -- "0..*" combate : participa_en >
combate "1" -- "0..*" pokemon : participa_en >